### ISSUE TITLE
Upgrade to Svelte 5

### ISSUE THREAD

**Issue by jimmy121192** [Gibbu/svoast#11]
Svelte 5 has been released, but Svoast is currently using Svelte 4, which is not compatible with the latest version.
![Screenshot 2024-11-18 092626](https://github.com/user-attachments/assets/ae75bb99-fa66-4b21-a2cf-1746496724d7)

**Comment by Gibbu** [comment]
Hey sorry about that mate, I've finally converted it to Svelte 5!

Install using: `svoast@3.0.1`.
Everything should still work the exact same, but let me know if you find anything!

**Comment by jimmy121192** [comment]
Thanks @Gibbu for the quick response. After I installed the new version ( 3.0.1) , I got an issue:
`[plugin:vite:import-analysis] Failed to resolve entry for package "svoast". The package may have incorrect main/module/exports specified in its package.json.`

Terminal log:

![Screenshot 2024-11-19 at 10 27 00 AM](https://github.com/user-attachments/assets/5a7fc5cd-faa9-46cc-ac59-067f8c28dd91)

![Screenshot 2024-11-19 at 10 23 52 AM](https://github.com/user-attachments/assets/972d4427-8e00-4e19-954f-f9313faff976)


I checked the svoast `packages.json` file and I saw this:
![Screenshot 2024-11-19 at 10 32 23 AM](https://github.com/user-attachments/assets/a363b485-8104-46c0-a4be-bc00d21a2b16)

![Screenshot 2024-11-19 at 10 35 31 AM](https://github.com/user-attachments/assets/3a7a1f94-5a7b-4170-9c8e-13d67856ca58)

I changed the paths to `./package/` so it could work for now.
Can you please update the fix? Thanks :)

**Comment by Gibbu** [comment]
Whoops, yeah I forgot to change that while copy/pasting it over.

`svoast@3.0.2` should fix this.

**Comment by jimmy121192** [comment]
Hi @Gibbu . Thanks for the fix.
However, there is still an error on the page where I use `import { toast } from 'svoast';`  :
<img width="590" alt="Screen Shot 2024-11-20 at 10 19 38 AM" src="https://github.com/user-attachments/assets/8258c998-e1c0-4380-bf8e-51fb0cca2737">

I checked the /node_modules/.vite/deps/svoast.js :
<img width="468" alt="Screen Shot 2024-11-20 at 10 24 59 AM" src="https://github.com/user-attachments/assets/784705b1-2739-40ea-a1df-5ec15271b595">

So, I need to change to `import { toaster } from 'svoast';`  to fix the problem. 
Could you release a new version with this fix ? (either by updating the documentation or changing the export name. I prefer the second one to avoid an extra migration guide ). Thanks.

**Comment by Gibbu** [comment]
Yeah wowee again, another thing I forgot to change...

Third time is a charm: `svoast@3.0.3`

**Comment by jimmy121192** [comment]
Thanks @Gibbu . It's all good now 🍾

**Comment by NormandoHall** [comment]
`svoast 3.0.3`

```
ReferenceError: toaster is not defined
    at Toasts (/opt/minerva/devel/node_modules/svoast/package/Toasts.svelte:23:9)
```

Using `svelte: 5.15.0` and` kit: 2.13.0`

The project is configured to use `js`
